# NUCLEAR DEPLOYMENT CONFIGURATION
# Nuclear ID: nuclear-1752430534646
# Timestamp: 2025-07-13T18:15:34.650Z

[build]
  command = "echo 'NUCLEAR DEPLOYMENT nuclear-1752430534646 - BYPASSING ALL CACHE'"
  publish = "."

[build.environment]
  NUCLEAR_ID = "nuclear-1752430534646"
  FORCE_NUCLEAR = "true"
  BUILD_VERSION = "4.10.5"

[[redirects]]
  from = "/"
  to = "/index-nuclear.html"
  status = 200
  force = true

[[redirects]]
  from = "/index.html"
  to = "/index-nuclear.html"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    ETag = "nuclear-1752430534646"
    X-Nuclear-Deployment = "nuclear-1752430534646"

[[headers]]
  for = "/build/v4.10.5/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    ETag = "nuclear-1752430534646-build"
    X-Nuclear-Files = "true"
