# Advanced Retirement Planner Netlify Configuration
# Deployment ID: deploy-1752415469639
# Build timestamp: 2025-07-13T14:04:29.639Z

[build]
  command = "echo 'Force deploying Advanced Retirement Planner v4.10.5 - deploy-1752415469639'"
  publish = "."

[build.environment]
  DEPLOYMENT_ID = "deploy-1752415469639"
  BUILD_TIMESTAMP = "2025-07-13T14:04:29.639Z"
  FORCE_REBUILD = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    ETag = "deploy-1752415469639"

[[headers]]
  for = "/src/core/*.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    ETag = "deploy-1752415469639-core"

[[headers]]
  for = "/src/utils/*.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    ETag = "deploy-1752415469639-utils"

[[headers]]
  for = "/src/styles/*.css"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    ETag = "deploy-1752415469639-styles"

[[headers]]
  for = "/version.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    ETag = "deploy-1752415469639-version"

# Redirect rules
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
