# EMERGENCY DEPLOYMENT CONFIGURATION
# Emergency ID: emergency-1752430896054
# Timestamp: 2025-07-13T18:21:36.058Z

[build]
  command = "echo 'EMERGENCY DEPLOYMENT emergency-1752430896054 - SIMPLE CACHE-BUSTING'"
  publish = "."

[build.environment]
  EMERGENCY_ID = "emergency-1752430896054"
  FORCE_REFRESH = "true"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    ETag = "emergency-1752430896054"
    X-Emergency-Fix = "emergency-1752430896054"

[[headers]]
  for = "/src/core/*.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    ETag = "emergency-1752430896054-core"

[[headers]]
  for = "/src/utils/*.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    ETag = "emergency-1752430896054-utils"
