# NETLIFY FIX CONFIGURATION
# Fix ID: netlify-fix-1752431602323
# Timestamp: 2025-07-13T18:33:22.326Z

[build]
  command = "echo 'NETLIFY FIX netlify-fix-1752431602323 - ROOT DIRECTORY DEPLOYMENT'"
  publish = "."
  ignore = "exit 0"

[build.environment]
  NETLIFY_FIX_ID = "netlify-fix-1752431602323"
  FORCE_ROOT_DEPLOYMENT = "true"
  NODE_VERSION = "18"

# Disable Vite framework detection
[build.processing]
  skip_processing = false

# Force headers for root directory
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    ETag = "netlify-fix-1752431602323"
    X-Netlify-Fix = "netlify-fix-1752431602323"
    X-Force-Refresh = "true"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    ETag = "netlify-fix-1752431602323-html"

[[headers]]
  for = "/src/core/*.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"  
    Expires = "0"
    ETag = "netlify-fix-1752431602323-core"

[[headers]]
  for = "/src/utils/*.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    ETag = "netlify-fix-1752431602323-utils"

[[headers]]
  for = "/version.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    ETag = "netlify-fix-1752431602323-version"
