name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

# Permissions for repository operations
permissions:
  contents: write
  pull-requests: write

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://ypollak2.github.io/advanced-retirement-planner/
    
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: main
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run full test suite
      run: npm test
      
    - name: Validate deployment readiness
      run: npm run validate:pre-work
      
    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        path: gh-pages-repo
        
    - name: Update production files in gh-pages root
      run: |
        # Copy all files from main branch to gh-pages root (but preserve stage folder)
        find . -maxdepth 1 \
          ! -name . \
          ! -name gh-pages-repo \
          ! -name .git \
          ! -name .github \
          ! -name node_modules \
          -exec cp -r {} gh-pages-repo/ \;
        
    - name: Commit and push to gh-pages
      run: |
        cd gh-pages-repo
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # Add changes (but don't remove stage folder)
        git add -A
        
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to deploy"
        else
          git commit -m "🎉 Deploy production: $(date '+%Y-%m-%d %H:%M:%S')"
          git push origin gh-pages
        fi
        
    - name: Validate production deployment
      run: |
        sleep 30
        npm run validate:deployment
        
    - name: Comment deployment URL
      uses: actions/github-script@v7
      with:
        script: |
          const repoName = context.payload.repository?.name || context.repo.repo;
          const repoOwner = context.payload.repository?.owner?.login || context.repo.owner;
          
          github.rest.repos.createCommitComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            commit_sha: context.sha,
            body: '🎉 **Production Deployment Complete!**\n\n' +
                  `**Production URL:** https://${repoOwner}.github.io/${repoName}/\n` +
                  '**Mirror URL:** https://advanced-retirement-planner.netlify.app/\n\n' +
                  '**Tests:** ✅ Full test suite passed\n' +
                  '**Validation:** ✅ Deployment validated\n' +
                  '**Status:** 🟢 Live for users\n\n' +
                  `**Commit:** ${context.sha.substring(0, 7)}\n` +
                  `**Branch:** ${context.ref.replace('refs/heads/', '')}\n` +
                  `**Deployed at:** ${new Date().toISOString()}`
          })