name: Deploy to Stage

on:
  push:
    branches: [ stage ]
  workflow_dispatch:

# Permissions needed for GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-stage:
    runs-on: ubuntu-latest
    environment: 
      name: stage
      url: https://ypollak2.github.io/advanced-retirement-planner/stage/
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Create stage directory structure
      run: |
        # Create _site directory for GitHub Pages
        mkdir -p _site/stage
        
        # Copy all files to stage subdirectory
        find . -maxdepth 1 ! -name . ! -name _site ! -name .git ! -name .github ! -name node_modules -exec cp -r {} _site/stage/ \;
        
        # Create a root redirect to production (optional)
        echo '<!DOCTYPE html>
        <html>
        <head>
          <meta http-equiv="refresh" content="0;url=https://ypollak2.github.io/advanced-retirement-planner/">
          <title>Redirecting...</title>
        </head>
        <body>
          <p>Redirecting to production... <a href="https://ypollak2.github.io/advanced-retirement-planner/">Click here if not redirected</a></p>
        </body>
        </html>' > _site/index.html
        
    - name: Setup GitHub Pages
      uses: actions/configure-pages@v4
      
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: _site
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      
    - name: Comment deployment URL
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.repos.createCommitComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            commit_sha: context.sha,
            body: '🚀 **Stage Deployment Complete!**\n\n' +
                  '**Stage URL:** https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/stage/\n\n' +
                  '**Tests:** ✅ All tests passed\n' +
                  '**Ready for:** Production merge review'
          })