# Disabled - Use Netlify's direct Git integration instead
# name: Deploy to Netlify

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3
#     
#     - name: Setup Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: '18'
#         cache: 'npm'
#     
#     - name: Install dependencies (if package.json exists)
#       run: |
#         if [ -f package.json ]; then
#           npm ci
#         fi
#     
#     - name: Skip build (deploy static files directly)
#       run: echo "Deploying static files directly - no build needed"
#     
#     - name: Deploy to Netlify
#       uses: netlify/actions/cli@master
#       with:
#         args: deploy --prod --dir=. --message="Deploy from GitHub Actions"
#       env:
#         NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
#         NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}