name: Security Scan

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security scan every Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  security-scan:
    runs-on: ubuntu-latest
    name: Security Vulnerability Scan
    permissions:
      contents: read
      security-events: write
      actions: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run npm audit
      run: npm audit --audit-level=moderate
      continue-on-error: true
    
    - name: Check for high severity vulnerabilities
      run: npm audit --audit-level=high
      continue-on-error: true
    
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v4
      with:
        languages: javascript
        queries: security-and-quality
      continue-on-error: true
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v4
      with:
        category: "/language:javascript"
        upload: true
      continue-on-error: true

  security-headers:
    runs-on: ubuntu-latest
    name: Security Headers Check
    permissions:
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Security Headers Analysis
      run: |
        echo "Checking security headers implementation..."
        
        # Check for CSP in HTML files
        if grep -r "Content-Security-Policy" *.html; then
          echo "✅ Content Security Policy found"
        else
          echo "⚠️ Content Security Policy not found"
        fi
        
        # Check for HTTPS enforcement
        if grep -r "https://" *.html; then
          echo "✅ HTTPS URLs found"
        else
          echo "⚠️ HTTPS enforcement check needed"
        fi
        
        # Check for secure headers in meta tags
        if grep -r "X-Content-Type-Options\|X-Frame-Options\|X-XSS-Protection" *.html; then
          echo "✅ Security headers found"
        else
          echo "⚠️ Security headers should be implemented"
        fi
    
    - name: Check for sensitive data
      run: |
        echo "Scanning for potential sensitive data..."
        
        # Check for potential API keys or secrets (excluding minified vendor files)
        if grep -r -i "api[_-]key\|secret\|password\|token" \
          --include="*.html" --include="*.js" --include="*.json" . \
          --exclude="package-lock.json" \
          --exclude-dir="node_modules" \
          --exclude-dir="deployment" \
          --exclude-dir="dist" \
          --exclude-dir="build" \
          --exclude="*vendor*.js" \
          --exclude="*bundle*.js" \
          --exclude="*chunk*.js" \
          --exclude="*min.js"; then
          echo "⚠️ Potential sensitive data found - please review"
          exit 1
        else
          echo "✅ No obvious sensitive data found"
        fi
    
    - name: JavaScript Security Check
      run: |
        echo "Checking JavaScript security..."
        
        # Check for eval usage (excluding minified vendor files)
        if grep -r "eval(" --include="*.html" --include="*.js" . \
          --exclude-dir="node_modules" \
          --exclude-dir="deployment" \
          --exclude-dir="dist" \
          --exclude-dir="build" \
          --exclude="*vendor*.js" \
          --exclude="*bundle*.js" \
          --exclude="*chunk*.js" \
          --exclude="*min.js"; then
          echo "⚠️ eval() usage found - security risk"
          exit 1
        else
          echo "✅ No eval() usage found"
        fi
        
        # Check for innerHTML usage (excluding minified vendor files)
        if grep -r "innerHTML" --include="*.html" --include="*.js" . \
          --exclude-dir="node_modules" \
          --exclude-dir="deployment" \
          --exclude-dir="dist" \
          --exclude-dir="build" \
          --exclude="*vendor*.js" \
          --exclude="*bundle*.js" \
          --exclude="*chunk*.js" \
          --exclude="*min.js"; then
          echo "⚠️ innerHTML usage found - check for XSS prevention"
        else
          echo "✅ No innerHTML usage found"
        fi
        
        # Check for document.write usage (excluding minified vendor files)
        if grep -r "document.write" --include="*.html" --include="*.js" . \
          --exclude-dir="node_modules" \
          --exclude-dir="deployment" \
          --exclude-dir="dist" \
          --exclude-dir="build" \
          --exclude="*vendor*.js" \
          --exclude="*bundle*.js" \
          --exclude="*chunk*.js" \
          --exclude="*min.js"; then
          echo "⚠️ document.write usage found - security risk"
          exit 1
        else
          echo "✅ No document.write usage found"
        fi

  license-check:
    runs-on: ubuntu-latest
    name: License Compliance Check
    permissions:
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check licenses
      run: |
        npx license-checker --summary --onlyAllow 'MIT;Apache-2.0;BSD-2-Clause;BSD-3-Clause;ISC;CC0-1.0;Unlicense;0BSD;CC-BY-3.0;CC-BY-4.0;(MIT AND CC-BY-3.0)'
      continue-on-error: true
    
    - name: Generate license report
      run: |
        npx license-checker --csv --out licenses.csv
        
    - name: Upload license report
      uses: actions/upload-artifact@v4
      with:
        name: license-report
        path: licenses.csv
        retention-days: 30